//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19Jul2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int EmplyeeId { get; set; }
        public System.DateTime PunchIn { get; set; }
        public Nullable<System.DateTime> PunchOut { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
