//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19Jul2020_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Reason { get; set; }
        public string Aproved { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
